on:
  push:
    branches:
    - master
    paths:
    - '*.md'
    - '**/*.md'
    - '**/**/*.md'
    - '**/**/**/**/*.md'
    - '**/**/**/**/**/*.md'

name: Generator - TOC
jobs:
  generateTOC:
    if: github.repository == 'GMC-Modding-Team/Community-Mod-Compilation-redux'
    name: Update the table of contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npx doctoc **.md --github | npx doctoc **/*.md --github | npx doctoc **/**/*.md --github | npx doctoc **/**/**/**/*.md --github | npx doctoc **/**/**/**/**/*.md --github
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "[Github] Update-toc"
          branch: "[Github] Update-toc"
          title: "[Github] Update-toc"
          body: |
            ```md
            - [x] Update TOC
            ```
